name: CI - Build & Test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout do código
        uses: actions/checkout@v4

      - name:  Configurar .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name:  Restaurar dependências
        run: dotnet restore

      - name:  Compilar solução
        run: dotnet build --configuration Release --no-restore

      - name:  Executar testes
        run: dotnet test --no-build --verbosity normal
