services:
  api-contatos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-contatos
    ports:
      - "44383:44383"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:44383"
    networks:
      - monitoring
    depends_on:
      - prometheus
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    ports:
      - "3000:3000"
    networks:
      - monitoring
    restart: unless-stopped

networks:
  monitoring:
    driver: bridge
