version: '3.8'

services:
  api-contatos:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: api-contatos
    ports:
      - "44383:80"
    volumes:
      - /mnt/c/Repositorio/tech-challenge/src/Contatos.Api:/app
    working_dir: /app
    command: ["dotnet", "Contatos.Api.dll"]  
    networks:
      - monitoring_net
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring_net
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'admin'
    networks:
      - monitoring_net
    depends_on:
      - prometheus
    restart: always

networks:
  monitoring_net:
    driver: bridge