apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'contatos-api'
        static_configs:
          - targets: ['contatos-api:8080']
        metrics_path: /metrics
